---
molecule_path: "py/examples/bond_stretching"
molecule: "LiH_distortions"
comment: "bond breaking"
distortion_dict:
    stretch_params: [-0.2, 0.2, 5]
    atom_bond_indices: [0, 1]
    equilibrium_geom: [["H", 0., 0., 0.], ["Li", 0., 0., 1.45]]
basis: "sto-3g"
transformation: ["jordan_wigner"]
benchmark: ["hf", "fci"]
benchmark_solver: "psi4"
active_space_method: ["frozen_core"]
ansatz:
    - ["kupccgsd", 1]
optimizer: ["BFGS"]
quantum_backend: 'QULACS'
samples: [0]
stages:
  - func: create_molecule
    args: [molecule, basis, active_space_method, molecule_path, mol_dist_id]  # mol_dist_id is a list that's created
    ret: molecule_qpfas

  - func: get_molecule_tq
    args: [molecule_qpfas, transformation]
    ret: molecule_tq

  - func: molecule_make_hamiltonian
    args: [molecule_tq]
    ret: qubit_hamiltonian_tq

  - func: vqe_wrapper
    args: [ansatz, qubit_hamiltonian_tq, molecule_tq, optimizer, samples, quantum_backend]
    ret: vqe_output

  - func: split_vqe_wrapper_results
    args: [vqe_output]
    ret: vqe_results

  - func: split_vqe_wrapper_ansatz
    args: [vqe_output]
    ret: vqe_ansatz

  - func: get_gate_dict
    args: [vqe_ansatz]
    ret: gate_stats

  - func: combine_results
    args: [vqe_results, molecule_qpfas, gate_stats]
    ret: results
